name: mendeleev_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.0.3
  flutter_svg: ^2.0.10+1
  flutter_localization: ^0.2.1
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sentry_flutter: ^8.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
